version: "3"
services:
  postgres:
    container_name: toadstool_postgres_db
    build:
      context: databases/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: toadstool
    ports:
      - 54321:5432
  sqlserver:
    container_name: toadstool_sqlserver_db
    build:
      context: databases/sqlserver
      dockerfile: Dockerfile
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Toadstool123
    ports:
      - 1433:1433
  mysql:
    container_name: toadstool_mysql_db
    build:
      context: databases/mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toadstool
      MYSQL_DATABASE: sakila
      MYSQL_USER: toadstool
      MYSQL_PASSWORD: toadstool
    ports:
      - 3306:3306
  wait-for:
    image: gesellix/wait-for
